// Copyright © KaKush LLC
// Written By Steven Zawaski
// Licensed to you under the MIT license

namespace Zerra.Repository.MariaDb
{
    public sealed partial class MariaDbEngine
    {
        private sealed class SqlColumnType
        {
            public string Table { get; set; } = null!;
            public string Column { get; set; } = null!;
            public string DataType { get; set; } = null!;
            public bool IsNullable { get; set; }
            public long? CharacterMaximumLength { get; set; }
            public uint? NumericPrecision { get; set; }
            public uint? NumericScale { get; set; }
            public uint? DatetimePrecision { get; set; }
            public bool IsAutoGenerated { get; set; }
            public bool IsPrimaryKey { get; set; }
        }
    }
}