// Copyright � KaKush LLC
// Written By Steven Zawaski
// Licensed to you under the MIT license

using Xunit;
using Npgsql;
using System.Text;
using Zerra.Repository.Reflection;
using Zerra.Repository.PostgreSql;

namespace Zerra.Repository.Test.PostgreSql
{
    public class PostgreSqlEngineTests
    {
        private static int ExecuteSql(string connectionString, string sql)
        {
            using (var connection = new NpgsqlConnection(connectionString))
            {
                connection.Open();
                using (var command = connection.CreateCommand())
                {
                    command.CommandText = sql;
                    return command.ExecuteNonQuery();
                }
            }
        }

        private static void DropDatabase(string connectionString)
        {
            var builder = new NpgsqlConnectionStringBuilder(connectionString);
            var testDatabase = builder.Database;
            builder.Database = "postgres";
            var connectionStringForMaster = builder.ToString();
            using (var connection = new NpgsqlConnection(connectionStringForMaster))
            {
                connection.Open();
                using (var command = connection.CreateCommand())
                {
                    command.CommandText = $"SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname='{testDatabase}';";
                    _ = command.ExecuteNonQuery();
                    command.CommandText = $"DROP DATABASE IF EXISTS {testDatabase};";
                    _ = command.ExecuteNonQuery();
                }
            }
        }


        [Fact]
        public async Task TestSequence()
        {
            var connectionString = PostgreSqlTestSqlDataContext.ConnectionString;
            var engine = PostgreSqlDataContext.GetEngine(connectionString);

            DropDatabase(connectionString);

            var modelTypes = new[] { typeof(TestTypesModel), typeof(TestRelationsModel) };

            CodeFirstGeneration.Generate(engine, DataStoreGenerationType.CodeFirst, modelTypes);
            RepoTest.AssertSchemaMatchesModels(engine, modelTypes);

            RepoTest.TestSequenceTransactStore(engine);
            await RepoTest.TestSequenceTransactStoreAsync(engine);

            const string changeColumn = "ALTER TABLE testtypes ALTER COLUMN int32thing TYPE bigint; ALTER TABLE testtypes ALTER COLUMN int32thing DROP NOT NULL;";
            const string addColumn = "ALTER TABLE testtypes ADD dummytomakenullable int NOT NULL";
            const string dropColmn = "ALTER TABLE testtypes DROP COLUMN bytething";
            _ = ExecuteSql(connectionString, changeColumn);
            _ = ExecuteSql(connectionString, addColumn);
            _ = ExecuteSql(connectionString, dropColmn);

            CodeFirstGeneration.Generate(engine, DataStoreGenerationType.CodeFirst, modelTypes);
            RepoTest.AssertSchemaMatchesModels(engine, modelTypes);

            var sb = new StringBuilder();
            var modelDetails = ModelAnalyzer.GetModel(typeof(TestTypesModel));
            foreach (var property in modelDetails.Members)
            {
                if (property.IsIdentity || property.IsIdentityAutoGenerated || property.IsRelated)
                    continue;
                if (modelDetails.Members.Any(x => x.ForeignIdentity == property.Name))
                    continue;
                _ = sb.Append("ALTER TABLE testtypes DROP COLUMN ").Append(property.PropertySourceName.ToLower()).Append(";\r\n");
            }
            var dropAllColumns = sb.ToString();

            _ = ExecuteSql(connectionString, dropAllColumns);

            CodeFirstGeneration.Generate(engine, DataStoreGenerationType.CodeFirst, modelTypes);
            RepoTest.AssertSchemaMatchesModels(engine, modelTypes);

            _ = sb.Clear();
            foreach (var property in modelDetails.Members)
            {
                if (property.IsIdentity || property.IsIdentityAutoGenerated || property.IsRelated)
                    continue;
                if (modelDetails.Members.Any(x => x.ForeignIdentity == property.Name))
                    continue;
                if (property.IsNullable)
                {
                    _ = sb.Append("ALTER TABLE testtypes ADD Junk").Append(property.PropertySourceName).Append(' ');
                    PostgreSqlEngine.WriteSqlTypeFromModel(sb, property);
                    PostgreSqlEngine.WriteTypeEndingFromModel(sb, property);
                    _ = sb.Insert(sb.Length - 4, "NOT ");
                    _ = sb.Append(";\r\n");
                }
            }
            var addJunkColumns = sb.ToString();

            _ = ExecuteSql(connectionString, addJunkColumns);

            CodeFirstGeneration.Generate(engine, DataStoreGenerationType.CodeFirst, modelTypes);
            RepoTest.AssertSchemaMatchesModels(engine, modelTypes);

            DropDatabase(connectionString);
        }
    }
}
