<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
        <PublishDocumentationFiles>false</PublishDocumentationFiles>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Framework\Zerra.CQRS.Kafka\Zerra.CQRS.Kafka.csproj" />
        <ProjectReference Include="..\..\..\Framework\Zerra.CQRS.RabbitMQ\Zerra.CQRS.RabbitMQ.csproj" />
        <ProjectReference Include="..\..\..\Framework\Zerra.Repository.Memory\Zerra.Repository.Memory.csproj" />
        <ProjectReference Include="..\..\..\Framework\Zerra.Repository.MsSql\Zerra.Repository.MsSql.csproj" />
        <!-- Only for KestrelCqrsClient, to publish events to the Shipping service over HTTP -->
        <ProjectReference Include="..\..\..\Framework\Zerra.Web\Zerra.Web.csproj" />
        <ProjectReference Include="..\Store.Catalog.Domain\Store.Catalog.Domain.csproj" />
        <ProjectReference Include="..\Store.Common\Store.Common.csproj" />
        <ProjectReference Include="..\Store.Inventory.Domain\Store.Inventory.Domain.csproj" />
        <ProjectReference Include="..\Store.Orders.Domain\Store.Orders.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Framework\Zerra.SourceGeneration\Zerra.SourceGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
