apiVersion: v1
kind: Namespace
metadata:
  name: zerrademo
  labels:
    name: zerrademo

---

apiVersion: v1
kind: Secret
metadata:
  name: zerrademo-registry
  namespace: zerrademo
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJzemF3YXNraSIsInBhc3N3b3JkIjoiZGNrcl9wYXRfT3JVaVJud1pZRmlWcXk3OVJPY2tXeEx5Qm9FIiwiYXV0aCI6ImMzcGhkMkZ6YTJrNlpHTnJjbDl3WVhSZlQzSlZhVkp1ZDFwWlJtbFdjWGszT1ZKUFkydFhlRXg1UW05RiJ9fX0=

---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
 # name: zerrademo-pets-mssql-volumeclaim
 # namespace: zerrademo
 # labels:
   # app: zerrademo-pets-mssql-volumeclaim
# spec:
 # accessModes:
   # - ReadWriteOnce
 # resources:
   # requests:
     # storage: 256Mi

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
 # name: zerrademo-ledger1-mssql-volumeclaim
 # namespace: zerrademo
 # labels:
   # app: zerrademo-ledger1-mssql-volumeclaim
# spec:
 # accessModes:
   # - ReadWriteOnce
 # resources:
   # requests:
     # storage: 256Mi

# ---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerrademo-pets-postgresql-volumeclaim
  namespace: zerrademo
  labels:
    app: zerrademo-pets-postgresql-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerrademo-ledger1-postgresql-volumeclaim
  namespace: zerrademo
  labels:
    app: zerrademo-ledger1-postgresql-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerrademo-ledger1-eventstore-data-volumeclaim
  namespace: zerrademo
  labels:
    app: zerrademo-ledger1-eventstore-data-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerrademo-ledger1-eventstore-log-volumeclaim
  labels:
    app: zerrademo-ledger1-eventstore-log-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerrademo-ledger2-eventstore-data-volumeclaim
  namespace: zerrademo
  labels:
    app: zerrademo-ledger2-eventstore-data-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerrademo-ledger2-eventstore-log-volumeclaim
  namespace: zerrademo
  labels:
    app: zerrademo-ledger2-eventstore-log-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
 # name: zerrademo-petsdomain-mssql
 # namespace: zerrademo
# spec:
 # selector:
   # matchLabels:
     # app: zerrademo-petsdomain-mssql-pod
 # template:
   # metadata:
     # labels:
       # app: zerrademo-petsdomain-mssql-pod
   # spec:
      # imagePullSecrets:
      # - name: zerrademo-registry
     # terminationGracePeriodSeconds: 30
     # containers:
     # - name: zerrademo-petsdomain-mssql-container
       # image: mcr.microsoft.com/mssql/server:2022-latest
       # ports:
          # - containerPort: 1433
       # env:
         # - name: MSSQL_PID
           # value: "Developer"
         # - name: ACCEPT_EULA
           # value: "Y"
         # - name: MSSQL_SA_PASSWORD
           # value: "Ld#dP22@uK4b"
       # volumeMounts:
         # - name: zerrademo-pets-mssql-volume
           # mountPath: /var/opt/mssql/data
     # volumes:
        # - name: zerrademo-pets-mssql-volume
          # persistentVolumeClaim:
            # claimName: zerrademo-pets-mssql-volumeclaim

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
 # name: zerrademo-ledger1domain-mssql
# spec:
 # selector:
   # matchLabels:
     # app: zerrademo-ledger1domain-mssql-pod
 # template:
   # metadata:
     # labels:
       # app: zerrademo-ledger1domain-mssql-pod
   # spec:
      # imagePullSecrets:
      # - name: zerrademo-registry
     # terminationGracePeriodSeconds: 30
     # containers:
     # - name: zerrademo-ledger1domain-mssql-container
       # image: mcr.microsoft.com/mssql/server:2019-latest
       # ports:
          # - containerPort: 1433
       # env:
         # - name: MSSQL_PID
           # value: "Developer"
         # - name: ACCEPT_EULA
           # value: "Y"
         # - name: SA_PASSWORD
           # value: "Ld#dP22@uK4b"
       # volumeMounts:
         # - name: zerrademo-ledger1-mssql-volume
           # mountPath: /var/opt/mssql/data
     # volumes:
        # - name: zerrademo-ledger1-mssql-volume
          # persistentVolumeClaim:
            # claimName: zerrademo-ledger1-mssql-volumeclaim

# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-petsdomain-postgresql
  namespace: zerrademo
spec:
  selector:
    matchLabels:
      app: zerrademo-petsdomain-postgresql-pod
  template:
    metadata:
      labels:
        app: zerrademo-petsdomain-postgresql-pod
    spec:
      imagePullSecrets:
      - name: zerrademo-registry
      terminationGracePeriodSeconds: 30
      containers:
      - name: zerrademo-petsdomain-postgresql-container
        image: postgres:latest
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "password123"
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - name: zerrademo-pets-postgresql-volume
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: zerrademo-pets-postgresql-volume
          persistentVolumeClaim:
            claimName: zerrademo-pets-postgresql-volumeclaim

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-ledger1domain-postgresql
  namespace: zerrademo
spec:
  selector:
    matchLabels:
      app: zerrademo-ledger1domain-postgresql-pod
  template:
    metadata:
      labels:
        app: zerrademo-ledger1domain-postgresql-pod
    spec:
      imagePullSecrets:
      - name: zerrademo-registry
      terminationGracePeriodSeconds: 30
      containers:
      - name: zerrademo-ledger1domain-postgresql-container
        image: postgres:latest
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "password123"
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - name: zerrademo-ledger1-postgresql-volume
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: zerrademo-ledger1-postgresql-volume
          persistentVolumeClaim:
            claimName: zerrademo-ledger1-postgresql-volumeclaim

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-ledger1domain-eventstore
  namespace: zerrademo
spec:
  selector:
    matchLabels:
      app: zerrademo-ledger1domain-eventstore-pod
  template:
    metadata:
      labels:
        app: zerrademo-ledger1domain-eventstore-pod
    spec:
      imagePullSecrets:
      - name: zerrademo-registry
      securityContext:
        fsGroup: 1000
      containers:
      - name: zerrademo-ledger1domain-eventstore-container
        image: eventstore/eventstore:latest
        ports:
           - containerPort: 1113
           - containerPort: 2113
        env:
          - name: EVENTSTORE_INSECURE
            value: "true"
          - name: EVENTSTORE_RUN_PROJECTIONS
            value: "All"
          - name: EVENTSTORE_EXT_TCP_PORT
            value: "1113"
          - name: EVENTSTORE_HTTP_PORT
            value: "2113"
        volumeMounts:
          - name: zerrademo-ledger1-eventstore-data-volume
            mountPath: /var/lib/eventstore
          - name: zerrademo-ledger1-eventstore-log-volume
            mountPath: /var/log/eventstore
      volumes:
        - name: zerrademo-ledger1-eventstore-data-volume
          persistentVolumeClaim:
            claimName: zerrademo-ledger1-eventstore-data-volumeclaim
        - name: zerrademo-ledger1-eventstore-log-volume
          persistentVolumeClaim:
            claimName: zerrademo-ledger1-eventstore-log-volumeclaim

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-ledger2domain-eventstore
  namespace: zerrademo
spec:
  selector:
    matchLabels:
      app: zerrademo-ledger2domain-eventstore-pod
  template:
    metadata:
      labels:
        app: zerrademo-ledger2domain-eventstore-pod
    spec:
      imagePullSecrets:
      - name: zerrademo-registry
      securityContext:
        fsGroup: 1000
      containers:
      - name: zerrademo-ledger2domain-eventstore-container
        image: eventstore/eventstore:latest
        ports:
           - containerPort: 1114
           - containerPort: 2114
        env:
          - name: EVENTSTORE_INSECURE
            value: "true"
          - name: EVENTSTORE_RUN_PROJECTIONS
            value: "All"
          - name: EVENTSTORE_EXT_TCP_PORT
            value: "1114"
          - name: EVENTSTORE_HTTP_PORT
            value: "2114"
        volumeMounts:
          - name: zerrademo-ledger2-eventstore-data-volume
            mountPath: /var/lib/eventstore
          - name: zerrademo-ledger2-eventstore-log-volume
            mountPath: /var/log/eventstore
      volumes:
        - name: zerrademo-ledger2-eventstore-data-volume
          persistentVolumeClaim:
            claimName: zerrademo-ledger2-eventstore-data-volumeclaim
        - name: zerrademo-ledger2-eventstore-log-volume
          persistentVolumeClaim:
            claimName: zerrademo-ledger2-eventstore-log-volumeclaim

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-petsdomain
  namespace: zerrademo
spec:
  selector:
    matchLabels:
      app: zerrademo-petsdomain-pod
  template:
    metadata:
      labels:
        app: zerrademo-petsdomain-pod
    spec:
      imagePullSecrets:
      - name: zerrademo-registry
      containers:
      - name: zerrademo-petsdomain-container
        image: szawaski/zerrademo-petsdomain
        imagePullPolicy: IfNotPresent
        env:
          - name: BindingUrl
            value: "+:80"
          - name: ZerraDemo.Service.Weather
            value: "zerrademo-weatherdomain-service:80"
          - name: PetsSqlConnectionStringMSSQL
            value: "Data Source=zerrademo-petsdomain-mssql-service,1433;Initial Catalog=ZerraDemoPets;User Id=sa;Password=Ld#dP22@uK4b;"
          - name: PetsSqlConnectionStringPOSTGRESQL
            value: "User ID=postgres;Password=password123;Host=zerrademo-petsdomain-postgresql-service;Port=5432;Database=zerrademopets;"
          - name: MessageHost
            value: my-cluster-kafka-external-bootstrap.kafka:31340
          - name: LogFileDirectory
            value: 
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 80
          name: mainport

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-weatherdomain
  namespace: zerrademo
spec:
  selector:
    matchLabels:
      app: zerrademo-weatherdomain-pod
  template:
    metadata:
      labels:
        app: zerrademo-weatherdomain-pod
    spec:
      imagePullSecrets:
      - name: zerrademo-registry
      containers:
      - name: zerrademo-weatherdomain-container
        image: szawaski/zerrademo-weatherdomain
        imagePullPolicy: IfNotPresent
        env:
          - name: BindingUrl
            value: "+:80"
          - name: MessageHost
            value: my-cluster-kafka-external-bootstrap.kafka:31340
          - name: LogFileDirectory
            value: 
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 80
          name: mainport
        
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-weathercacheddomain
  namespace: zerrademo
spec:
  selector:
    matchLabels:
      app: zerrademo-weathercacheddomain-pod
  template:
    metadata:
      labels:
        app: zerrademo-weathercacheddomain-pod
    spec:
      imagePullSecrets:
      - name: zerrademo-registry
      containers:
      - name: zerrademo-weathercacheddomain-container
        image: szawaski/zerrademo-weathercacheddomain
        imagePullPolicy: IfNotPresent
        env:
          - name: BindingUrl
            value: "+:80"
          - name: MessageHost
            value: my-cluster-kafka-external-bootstrap.kafka:31340
          - name: LogFileDirectory
            value: 
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 80
          name: mainport

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-ledger1domain
  namespace: zerrademo
spec:
  selector:
    matchLabels:
      app: zerrademo-ledger1domain-pod
  template:
    metadata:
      labels:
        app: zerrademo-ledger1domain-pod
    spec:
      imagePullSecrets:
      - name: zerrademo-registry
      containers:
      - name: zerrademo-ledger1domain-container
        image: szawaski/zerrademo-ledger1domain
        imagePullPolicy: IfNotPresent
        env:
          - name: BindingUrl
            value: "+:80"
          - name: Ledger1SqlConnectionStringMSSQL
            value: "Data Source=zerrademo-ledger1domain-mssql-service,1433;Initial Catalog=ZerraDemoLedger;User Id=sa;Password=Ld#dP22@uK4b;"
          - name: Ledger1SqlConnectionStringPOSTGRESQL
            value: "User ID=postgres;Password=password123;Host=zerrademo-ledger1domain-postgresql-service;Port=5432;Database=zerrademoledger;"
          - name: Ledger1EventStoreServer
            value: "tcp://zerrademo-ledger1domain-eventstore-service:2113"
          - name: MessageHost
            value: my-cluster-kafka-external-bootstrap.kafka:31340
          - name: LogFileDirectory
            value: 
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 80
          name: mainport
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-ledger2domain
  namespace: zerrademo
spec:
  selector:
    matchLabels:
      app: zerrademo-ledger2domain-pod
  template:
    metadata:
      labels:
        app: zerrademo-ledger2domain-pod
    spec:
      imagePullSecrets:
      - name: zerrademo-registry
      containers:
      - name: zerrademo-ledger2domain-container
        image: szawaski/zerrademo-ledger2domain
        imagePullPolicy: IfNotPresent
        env:
          - name: BindingUrl
            value: "+:80"
          - name: Ledger2EventStoreServer
            value: "tcp://zerrademo-ledger2domain-eventstore-service:2114"
          - name: MessageHost
            value: my-cluster-kafka-external-bootstrap.kafka:31340
          - name: LogFileDirectory
            value: 
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 80
          name: mainport

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerrademo-web
  namespace: zerrademo
spec:
  selector:
    matchLabels:
      app: zerrademo-web-pod
  template:
    metadata:
      labels:
        app: zerrademo-web-pod
    spec:
      imagePullSecrets:
      - name: zerrademo-registry
      containers:
      - name: zerrademo-web-container
        image: szawaski/zerrademo-web
        imagePullPolicy: IfNotPresent
        env:
          - name: ZerraDemo.Service.Pets
            value: "zerrademo-petsdomain-service:80"
          - name: ZerraDemo.Service.Weather
            value: "zerrademo-weatherdomain-service:80"
          - name: ZerraDemo.Service.WeatherCached
            value: "zerrademo-weathercacheddomain-service:80"
          - name: ZerraDemo.Service.Ledger1
            value: "zerrademo-ledger1domain-service:80"
          - name: ZerraDemo.Service.Ledger2
            value: "zerrademo-ledger2domain-service:80"
          - name: MessageHost
            value: my-cluster-kafka-external-bootstrap.kafka:31340
          - name: LogFileDirectory
            value: 
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 80
          name: mainport
---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-ledger1domain-eventstore-service
  namespace: zerrademo
spec:
  selector:
    app: zerrademo-ledger1domain-eventstore-pod
  ports:
  - port: 1113
    targetPort: 1113
    name: tcp
  - port: 2113
    targetPort: 2113
    name: http
    
---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-ledger2domain-eventstore-service
  namespace: zerrademo
spec:
  selector:
    app: zerrademo-ledger2domain-eventstore-pod
  ports:
  - port: 1114
    targetPort: 1114
    name: tcp
  - port: 2114
    targetPort: 2114
    name: http
  
---

# apiVersion: v1
# kind: Service
# metadata:
 # name: zerrademo-petsdomain-mssql-service
 # namespace: zerrademo
# spec:
 # selector:
   # app: zerrademo-petsdomain-mssql-pod
 # ports:
 # - port: 1433
   # targetPort: 1433
 
# ---

# apiVersion: v1
# kind: Service
# metadata:
 # name: zerrademo-ledger1domain-mssql-service
 # namespace: zerrademo
# spec:
 # selector:
   # app: zerrademo-ledger1domain-mssql-pod
 # ports:
 # - port: 1433
   # targetPort: 1433
 
# ---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-petsdomain-postgresql-service
  namespace: zerrademo
spec:
  selector:
    app: zerrademo-petsdomain-postgresql-pod
  ports:
  - port: 5432
    targetPort: 5432
  
---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-ledger1domain-postgresql-service
  namespace: zerrademo
spec:
  selector:
    app: zerrademo-ledger1domain-postgresql-pod
  ports:
  - port: 5432
    targetPort: 5432
  
---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-petsdomain-service
  namespace: zerrademo
spec:
  selector:
    app: zerrademo-petsdomain-pod
  ports:
  - port: 80
    targetPort: mainport

---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-weatherdomain-service
  namespace: zerrademo
spec:
  selector:
    app: zerrademo-weatherdomain-pod
  ports:
  - port: 80
    targetPort: mainport

---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-weathercacheddomain-service
  namespace: zerrademo
spec:
  selector:
    app: zerrademo-weathercacheddomain-pod
  ports:
  - port: 80
    targetPort: mainport

---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-ledger1domain-service
  namespace: zerrademo
spec:
  selector:
    app: zerrademo-ledger1domain-pod
  ports:
  - port: 80
    targetPort: mainport
  
---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-ledger2domain-service
  namespace: zerrademo
spec:
  selector:
    app: zerrademo-ledger2domain-pod
  ports:
  - port: 80
    targetPort: mainport  

---

apiVersion: v1
kind: Service
metadata:
  name: zerrademo-web-service
  namespace: zerrademo
spec:
  selector:
    app: zerrademo-web-pod
  ports:
  - port: 80
    targetPort: mainport
    nodePort: 30000
  type: NodePort
  