// Copyright © KaKush LLC
// Written By Steven Zawaski
// Licensed to you under the MIT license

using System;

namespace Zerra.Repository
{
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
    public sealed class IdentityAttribute : Attribute
    {
        public bool AutoGenerated { get; }
        public IdentityAttribute()
        {
        }
        public IdentityAttribute(bool autoGenerated)
        {
            this.AutoGenerated = autoGenerated;
        }
    }
}
