// Copyright © KaKush LLC
// Written By Steven Zawaski
// Licensed to you under the MIT license

namespace Zerra.Repository
{
    /// <summary>
    /// Marks a property or field as the identity (primary key) of a data store entity.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
    public sealed class IdentityAttribute : Attribute
    {
        /// <summary>Gets a value indicating whether the identity value is automatically generated by the data store.</summary>
        public bool AutoGenerated { get; }

        /// <summary>Initializes a new instance of <see cref="IdentityAttribute"/>.</summary>
        public IdentityAttribute()
        {
        }

        /// <summary>Initializes a new instance of <see cref="IdentityAttribute"/> specifying whether the identity is auto-generated.</summary>
        /// <param name="autoGenerated"><see langword="true"/> if the data store generates the identity value automatically; otherwise, <see langword="false"/>.</param>
        public IdentityAttribute(bool autoGenerated)
        {
            this.AutoGenerated = autoGenerated;
        }
    }
}
