// Copyright © KaKush LLC
// Written By Steven Zawaski
// Licensed to you under the MIT license

using System;
using System.Linq;
using System.Reflection;
using Zerra.Reflection;

namespace Zerra.Repository.Reflection
{
    public sealed class ModelPropertyDetail
    {
        public MemberInfo MemberInfo { get; private set; }
        public bool IsDataSourceEntity { get; private set; }

        public string Name { get; private set; }
        public Type Type { get; private set; }
        public CoreType? CoreType { get; private set; }
        public string PropertySourceName { get; private set; }
        public bool IsIdentity { get; private set; } //Usually maps to DB PrimaryKey
        public bool IsIdentityAutoGenerated { get; private set; } //Usually maps to DB Identity Specification (Auto Increment)
        public bool IsRelated { get; private set; }
        public string? ForeignIdentity { get; private set; }
        public bool IsEnumerable { get; private set; }
        public bool IsNullable { get; private set; }
        public Type InnerType { get; private set; }
        public CoreType? InnerCoreType { get; private set; }
        public bool IsDataSourceNotNull { get; private set; }
        public int? DataSourcePrecisionLength { get; private set; }
        public int? DataSourceScale { get; private set; }
        public StoreTextEncoding TextEncoding { get; private set; }
        public StoreDatePart DatePart { get; private set; }

        public Func<object, object?> Getter { get; private set; }
        public Action<object, object?> Setter { get; private set; }

        public object CoreTypeSetter { get; private set; }

        public override string ToString()
        {
            return $"{Type.Name} {Name}";
        }

        internal ModelPropertyDetail(MemberDetail memberDetail, bool declaringTypeIsDataSourceEntity)
        {
            this.MemberInfo = memberDetail.MemberInfo;

            this.Name = memberDetail.Name;
            this.Type = memberDetail.Type;
            this.CoreType = memberDetail.TypeDetail.CoreType;
            this.IsNullable = memberDetail.TypeDetail.IsNullable;
            this.IsEnumerable = memberDetail.TypeDetail.IsIEnumerable;
            this.InnerType = memberDetail.TypeDetail.InnerTypes?.Count > 0 ? memberDetail.TypeDetail.InnerTypes[0] : memberDetail.TypeDetail.Type;
            this.InnerCoreType = memberDetail.TypeDetail.InnerTypes?.Count > 0 ? memberDetail.TypeDetail.InnerTypeDetails[0].CoreType : memberDetail.TypeDetail.CoreType;

            var sourcePropertyAttribute = memberDetail.Attributes.Select(x => x as StoreNameAttribute).Where(x => x != null).FirstOrDefault();
            var storeName = sourcePropertyAttribute?.StoreName;
            if (String.IsNullOrWhiteSpace(storeName))
                storeName = memberDetail.Name;
            if (!storeName.All(x => Char.IsLetterOrDigit(x) || x == '_' || x == '`'))
                throw new ArgumentException($"{nameof(StoreNameAttribute)}.{nameof(StoreNameAttribute.StoreName)}={storeName}");
            this.PropertySourceName = storeName;

            IdentityAttribute? identityAttribute = null;
            RelationAttribute? foreignIdentityAttribute = null;
            if (declaringTypeIsDataSourceEntity)
            {
                identityAttribute = memberDetail.Attributes.Select(x => x as IdentityAttribute).Where(x => x != null).FirstOrDefault();
                foreignIdentityAttribute = memberDetail.Attributes.Select(x => x as RelationAttribute).Where(x => x != null).FirstOrDefault();
            }
            this.IsIdentity = identityAttribute != null;
            this.ForeignIdentity = foreignIdentityAttribute?.ForeignIdentity;
            this.IsIdentityAutoGenerated = identityAttribute != null && identityAttribute.AutoGenerated;
            this.IsRelated = foreignIdentityAttribute != null;

            var entityAttribute = memberDetail.TypeDetail.Attributes.Select(x => x as EntityAttribute).Where(x => x != null).FirstOrDefault();
            this.IsDataSourceEntity = entityAttribute != null;

            var storePropertyAttribute = memberDetail.Attributes.Select(x => x as StorePropertiesAttribute).Where(x => x != null).FirstOrDefault();
            this.IsDataSourceNotNull = storePropertyAttribute != null ? storePropertyAttribute.NotNull : (InnerType.IsValueType && !memberDetail.TypeDetail.IsNullable);
            this.DataSourcePrecisionLength = storePropertyAttribute != null ? storePropertyAttribute.PrecisionLength : null;
            this.DataSourceScale = storePropertyAttribute != null ? storePropertyAttribute.Scale : null;
            this.TextEncoding = storePropertyAttribute != null ? storePropertyAttribute.TextEncoding : StoreTextEncoding.Unicode;
            this.DatePart = storePropertyAttribute != null ? storePropertyAttribute.DatePart : StoreDatePart.DateTime;

            if (!this.IsDataSourceNotNull && this.IsIdentity)
                throw new Exception($"{this.Type.GetNiceName()} {this.Name} cannot be both an identity and nullable");

            this.Getter = memberDetail.Getter;
            this.Setter = memberDetail.Setter;

            this.CoreTypeSetter = CoreTypeSetterGenerator.Get(this.MemberInfo, this.CoreType, this.Type.IsArray && this.InnerCoreType == Zerra.Reflection.CoreType.Byte);
        }
    }
}
