// Copyright © KaKush LLC
// Written By Steven Zawaski
// Licensed to you under the MIT license

using System;
using System.Collections.Generic;
using System.Linq;
using Zerra.Reflection;

namespace Zerra.Repository.Reflection
{
    public class ModelDetail
    {
        public Type Type { get; private set; }
        public string Name { get; private set; }
        public bool IsDataSourceEntity { get; private set; }
        public string DataSourceEntityName { get; private set; }
        public IReadOnlyList<ModelPropertyDetail> Properties { get; private set; }
        public IReadOnlyList<ModelPropertyDetail> IdentityProperties { get; private set; }
        public IReadOnlyList<ModelPropertyDetail> IdentityAutoGeneratedProperties { get; private set; }
        public IReadOnlyList<ModelPropertyDetail> RelatedProperties { get; private set; }
        public IReadOnlyList<ModelPropertyDetail> RelatedEnumerableProperties { get; private set; }
        public IReadOnlyList<ModelPropertyDetail> RelatedNonEnumerableProperties { get; private set; }
        public IReadOnlyList<ModelPropertyDetail> NonAutoGeneratedNonRelationProperties { get; private set; }

        private readonly IDictionary<string, ModelPropertyDetail> propertiesByName;
        public ModelPropertyDetail GetProperty(string name)
        {
            if (!this.propertiesByName.TryGetValue(name, out ModelPropertyDetail property))
                throw new Exception($"{nameof(ModelDetail)} for {Type.Name} does not contain property {name}");
            return property;
        }
        public bool TryGetProperty(string name, out ModelPropertyDetail property)
        {
            return this.propertiesByName.TryGetValue(name, out property);
        }

        private readonly IDictionary<string, ModelPropertyDetail> propertiesByNameLower;
        public ModelPropertyDetail GetPropertyLower(string name)
        {
            if (!this.propertiesByNameLower.TryGetValue(name, out ModelPropertyDetail property))
                throw new Exception($"{nameof(ModelDetail)} for {Type.Name} does not contain property {name}");
            return property;
        }
        public bool TryGetPropertyLower(string name, out ModelPropertyDetail property)
        {
            return this.propertiesByNameLower.TryGetValue(name, out property);
        }

        public Func<object> Creator { get; set; }

        public override string ToString()
        {
            return Type.GetNiceFullName();
        }

        internal ModelDetail(TypeDetail typeDetails)
        {
            this.Type = typeDetails.Type;
            while (typeDetails.InnerTypes.Count == 1)
            {
                this.Type = typeDetails.InnerTypes[0];
                typeDetails = typeDetails.InnerTypeDetails[0];
            }

            var sourceEntityAttribute = typeDetails.Attributes.Select(x => x as DataSourceEntityAttribute).Where(x => x != null).FirstOrDefault();
            this.IsDataSourceEntity = sourceEntityAttribute != null;
            if (this.IsDataSourceEntity)
            {
                this.DataSourceEntityName = sourceEntityAttribute.SourceName;
                if (String.IsNullOrWhiteSpace(this.DataSourceEntityName))
                    this.DataSourceEntityName = this.Type.Name;
                if (!this.DataSourceEntityName.All(x => char.IsLetterOrDigit(x) || x == '_' || x == '`'))
                    throw new ArgumentException(String.Format("{0}.{1}={2}", nameof(DataSourceEntityAttribute), nameof(DataSourceEntityAttribute.SourceName), this.DataSourceEntityName));
            }

            var modelProperties = new List<ModelPropertyDetail>();
            foreach (var member in typeDetails.MemberDetails)
            {
                var notSourcePropertyAttribute = member.Attributes.Select(x => x as NotDataSourcePropertyAttribute).Where(x => x != null).FirstOrDefault();
                if (notSourcePropertyAttribute == null)
                {
                    var modelPropertyInfo = new ModelPropertyDetail(member, this.IsDataSourceEntity);
                    modelProperties.Add(modelPropertyInfo);
                }
            }

            this.Name = typeDetails.Type.Name;
            this.Properties = modelProperties.ToArray();

            this.propertiesByName = this.Properties.ToDictionary(x => x.Name);
            this.propertiesByNameLower = this.Properties.ToDictionary(x => x.Name.ToLower());
            this.IdentityProperties = this.Properties.Where(x => x.IsIdentity).ToArray();
            this.IdentityAutoGeneratedProperties = this.Properties.Where(x => x.IsIdentity && x.IsIdentityAutoGenerated).ToArray();
            this.RelatedProperties = this.Properties.Where(x => x.IsRelated).ToArray();
            this.RelatedEnumerableProperties = this.Properties.Where(x => x.IsRelated && x.IsEnumerable).ToArray();
            this.RelatedNonEnumerableProperties = this.Properties.Where(x => x.IsRelated && !x.IsEnumerable).ToArray();
            this.NonAutoGeneratedNonRelationProperties = this.Properties.Where(x => !x.IsIdentityAutoGenerated && !x.IsRelated).ToArray();

            this.Creator = typeDetails.Creator;
            if (this.Creator == null)
                throw new Exception($"{Type.Name} must have a parameterless constructor to be a model.");
        }
    }
}
