// Copyright © KaKush LLC
// Written By Steven Zawaski
// Licensed to you under the MIT license

using System;
using System.Linq;
using System.Reflection;
using Zerra.Reflection;

namespace Zerra.Repository.Reflection
{
    public class ModelPropertyDetail
    {
        public MemberInfo MemberInfo { get; private set; }
        public bool IsDataSourceEntity { get; private set; }

        public string Name { get; private set; }
        public Type Type { get; private set; }
        public CoreType? CoreType { get; private set; }
        public string PropertySourceName { get; private set; }
        public bool IsIdentity { get; private set; } //Usually maps to DB PrimaryKey
        public bool IsIdentityAutoGenerated { get; private set; } //Usually maps to DB Identity Specification (Auto Increment)
        public bool IsRelated { get; private set; }
        public string ForeignIdentity { get; private set; }
        public bool IsEnumerable { get; private set; }
        public bool IsNullable { get; private set; }
        public Type InnerType { get; private set; }
        public CoreType? InnerCoreType { get; private set; }
        public bool IsDataSourceNotNull { get; private set; }
        public int? DataSourcePrecisionLength { get; private set; }
        public int? DataSourceScale { get; private set; }

        public Func<object, object> Getter { get; private set; }
        public Action<object, object> Setter { get; private set; }

        public object CoreTypeSetter { get; private set; }

        public override string ToString()
        {
            return $"{Type.Name} {Name}";
        }

        internal ModelPropertyDetail(MemberDetail memberDetail, bool declaringTypeIsDataSourceEntity)
        {
            this.MemberInfo = memberDetail.MemberInfo;

            this.Name = memberDetail.Name;
            this.Type = memberDetail.Type;
            this.CoreType = memberDetail.TypeDetail.CoreType;
            this.IsNullable = memberDetail.TypeDetail.IsNullable;
            this.IsEnumerable = memberDetail.TypeDetail.IsIEnumerable;
            this.InnerType = memberDetail.TypeDetail.InnerTypes?.Count > 0 ? memberDetail.TypeDetail.InnerTypes[0] : memberDetail.TypeDetail.Type;
            this.InnerCoreType = memberDetail.TypeDetail.InnerTypes?.Count > 0 ? memberDetail.TypeDetail.InnerTypeDetails[0].CoreType : memberDetail.TypeDetail.CoreType;

            var sourcePropertyAttribute = memberDetail.Attributes.Select(x => x as DataSourcePropertyAttribute).Where(x => x != null).FirstOrDefault();
            this.PropertySourceName = sourcePropertyAttribute?.SourceName;
            if (String.IsNullOrWhiteSpace(this.PropertySourceName))
                this.PropertySourceName = memberDetail.Name;
            if (!this.PropertySourceName.All(x => char.IsLetterOrDigit(x) || x == '_' || x == '`'))
                throw new ArgumentException(String.Format("{0}.{1}={2}", nameof(DataSourcePropertyAttribute), nameof(DataSourcePropertyAttribute.SourceName), this.PropertySourceName));

            IdentityAttribute identityAttribute = null;
            DataSourceRelationAttribute foreignIdentityAttribute = null;
            if (declaringTypeIsDataSourceEntity)
            {
                identityAttribute = memberDetail.Attributes.Select(x => x as IdentityAttribute).Where(x => x != null).FirstOrDefault();
                foreignIdentityAttribute = memberDetail.Attributes.Select(x => x as DataSourceRelationAttribute).Where(x => x != null).FirstOrDefault();
            }
            this.IsIdentity = identityAttribute != null;
            this.ForeignIdentity = foreignIdentityAttribute?.ForeignIdentity;
            this.IsIdentityAutoGenerated = identityAttribute != null && identityAttribute.AutoGenerated;
            this.IsRelated = foreignIdentityAttribute != null;

            var dataSourceEntityAttribute = memberDetail.TypeDetail.Attributes.Select(x => x as DataSourceEntityAttribute).Where(x => x != null).FirstOrDefault();
            this.IsDataSourceEntity = dataSourceEntityAttribute != null;

            var dataSourceTypeAttribute = memberDetail.Attributes.Select(x => x as DataSourceTypeAttribute).Where(x => x != null).FirstOrDefault();
            this.IsDataSourceNotNull = dataSourceTypeAttribute != null ? dataSourceTypeAttribute.NotNull : (InnerType.IsValueType && !memberDetail.TypeDetail.IsNullable);
            this.DataSourcePrecisionLength = dataSourceTypeAttribute != null ? dataSourceTypeAttribute.PrecisionLength : null;
            this.DataSourceScale = dataSourceTypeAttribute != null ? dataSourceTypeAttribute.Scale : null;

            if (!this.IsDataSourceNotNull && this.IsIdentity)
                throw new Exception($"{this.Type.GetNiceName()} {this.Name} cannot be both an identity and nullable");

            this.Getter = memberDetail.Getter;
            this.Setter = memberDetail.Setter;

            var genericCoreTypeSetter = TypeAnalyzer.GetGenericTypeDetail(typeof(CoreTypeSetter<>), memberDetail.MemberInfo.DeclaringType);
            this.CoreTypeSetter = genericCoreTypeSetter.GetConstructor(new Type[] { typeof(CoreType?), typeof(bool), typeof(object) }).Creator(new object[] { this.CoreType, this.Type.IsArray && this.InnerCoreType == Zerra.Reflection.CoreType.Byte, memberDetail.SetterTyped });
        }
    }
}
