// Copyright © KaKush LLC
// Written By Steven Zawaski
// Licensed to you under the MIT license

using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using Zerra.Reflection;

namespace Zerra.Repository.Reflection
{
    /// <summary>
    /// Holds reflected metadata about a repository model type, including members lists categorised
    /// by identity, relation, and data-source characteristics.
    /// </summary>
    public sealed class ModelDetail
    {
        /// <summary>
        /// The underlying <see cref="Zerra.Reflection.TypeDetail"/> for this model type.
        /// </summary>
        public TypeDetail TypeDetail { get; }
        /// <summary>
        /// The CLR <see cref="System.Type"/> of this model.
        /// </summary>
        public Type Type { get; }
        /// <summary>
        /// The simple name of the model type.
        /// </summary>
        public string Name { get; }

        /// <summary>
        /// The closed <c>Func&lt;T, bool&gt;</c> delegate type used when building LINQ predicate expressions for this model.
        /// </summary>
        public Type LambdaDelegateType { get; }

        private readonly string? dataSourceEntityName;
        /// <summary>
        /// Gets a value indicating whether this type is decorated with <see cref="EntityAttribute"/>.
        /// </summary>
        public bool IsDataSourceEntity => dataSourceEntityName is not null;
        /// <summary>
        /// The store or table name for this model, as specified by <see cref="EntityAttribute"/> or defaulting to the type name.
        /// </summary>
        /// <exception cref="Exception">Thrown when the type does not have an <see cref="EntityAttribute"/>.</exception>
        public string DataSourceEntityName => dataSourceEntityName ?? throw new Exception($"{Type.Name} does not have an EntityAttribute");
        /// <summary>
        /// All model members that are not excluded by <see cref="StoreExcludeAttribute"/>.
        /// </summary>
        public IReadOnlyList<ModelMemberDetail> Members { get; }
        /// <summary>
        /// Properties marked with <see cref="IdentityAttribute"/>; typically the primary key column(s).
        /// </summary>
        public IReadOnlyList<ModelMemberDetail> IdentityMembers { get; }
        /// <summary>
        /// Identity members whose values are auto-generated by the data source (e.g. auto-increment / DB identity).
        /// </summary>
        public IReadOnlyList<ModelMemberDetail> IdentityAutoGeneratedMembers { get; }
        /// <summary>
        /// Properties marked with <see cref="RelationAttribute"/>; represent foreign-key relationships.
        /// </summary>
        public IReadOnlyList<ModelMemberDetail> RelatedMembers { get; }
        /// <summary>
        /// Related members whose type implements <see cref="System.Collections.Generic.IEnumerable{T}"/>; represent one-to-many relationships.
        /// </summary>
        public IReadOnlyList<ModelMemberDetail> RelatedEnumerableMembers { get; }
        /// <summary>
        /// Related members whose type does not implement <see cref="System.Collections.Generic.IEnumerable{T}"/>; represent many-to-one or one-to-one relationships.
        /// </summary>
        public IReadOnlyList<ModelMemberDetail> RelatedNonEnumerableMembers { get; }
        /// <summary>
        /// Properties that are neither auto-generated identity columns nor relation members.
        /// </summary>
        public IReadOnlyList<ModelMemberDetail> NonAutoGeneratedNonRelationMembers { get; }

        internal bool ForeignReferenceLoadCompleted { get; private set; } = false;
        internal void MarkForeignReferenceLoadCompleted()
        {
            ForeignReferenceLoadCompleted = true;
        }

        private readonly IDictionary<string, ModelMemberDetail> membersByName;
        /// <summary>
        /// Returns the <see cref="ModelMemberDetail"/> whose name exactly matches <paramref name="name"/>.
        /// </summary>
        /// <param name="name">The case-sensitive member name.</param>
        /// <returns>The matching <see cref="ModelMemberDetail"/>.</returns>
        /// <exception cref="Exception">Thrown when no member with the given name exists.</exception>
        public ModelMemberDetail GetMember(string name)
        {
            if (!this.membersByName.TryGetValue(name, out var member))
                throw new Exception($"{nameof(ModelDetail)} for {Type.Name} does not contain member {name}");
            return member;
        }
        /// <summary>
        /// Attempts to find a <see cref="ModelMemberDetail"/> by its exact name.
        /// </summary>
        /// <param name="name">The case-sensitive member name.</param>
        /// <param name="member">When successful, the matching <see cref="ModelMemberDetail"/>; otherwise <see langword="null"/>.</param>
        /// <returns><see langword="true"/> if the member was found; otherwise <see langword="false"/>.</returns>
        public bool TryGetProperty(string name,
#if !NETSTANDARD2_0
            [MaybeNullWhen(false)]
#endif
        out ModelMemberDetail member)
        {
            return this.membersByName.TryGetValue(name, out member);
        }

        private readonly Dictionary<string, ModelMemberDetail> membersByNameLower;
        /// <summary>
        /// Returns the <see cref="ModelMemberDetail"/> whose lowercase name matches the lowercase form of <paramref name="name"/>.
        /// </summary>
        /// <param name="name">The member name to look up (case-insensitive).</param>
        /// <returns>The matching <see cref="ModelMemberDetail"/>.</returns>
        /// <exception cref="Exception">Thrown when no member with the given name exists.</exception>
        public ModelMemberDetail GetMemberLower(string name)
        {
            if (!this.membersByNameLower.TryGetValue(name, out var member))
                throw new Exception($"{nameof(ModelDetail)} for {Type.Name} does not contain member {name}");
            return member;
        }
        /// <summary>
        /// Attempts to find a <see cref="ModelMemberDetail"/> by a case-insensitive member name lookup.
        /// </summary>
        /// <param name="name">The member name to look up (case-insensitive).</param>
        /// <param name="member">When successful, the matching <see cref="ModelMemberDetail"/>; otherwise <see langword="null"/>.</param>
        /// <returns><see langword="true"/> if the member was found; otherwise <see langword="false"/>.</returns>
        public bool TryGetPropertyLower(string name,
#if !NETSTANDARD2_0
            [MaybeNullWhen(false)]
#endif
        out ModelMemberDetail member)
        {
            return this.membersByNameLower.TryGetValue(name, out member);
        }

        /// <summary>
        /// A boxed parameterless factory delegate that creates a new instance of the model type.
        /// </summary>
        public Func<object> Creator { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            return $"{Type.Name} {Name}";
        }

        internal ModelDetail(TypeDetail typeDetail)
        {
            this.TypeDetail = typeDetail;
            this.Type = typeDetail.Type;

            try
            {
#pragma warning disable IL3050 // Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.
                this.LambdaDelegateType = typeof(Func<,>).MakeGenericType(this.Type, typeof(bool));
#pragma warning restore IL3050 // Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.
            }
            catch (Exception ex)
            {
                if (!RuntimeFeature.IsDynamicCodeSupported)
                    throw new InvalidOperationException($"Failed to create lambda delegate type for {this.Type.FullName}. Dynamic code execution is not supported in this runtime environment.", ex);
                throw;
            }

            if (!typeDetail.HasCreator)
                throw new Exception($"{Type.Name} must have a parameterless constructor to be a model.");

            while (typeDetail.InnerTypes.Count == 1)
            {
                this.Type = typeDetail.InnerType!;
                typeDetail = typeDetail.InnerTypeDetail!;
            }

            var sourceEntityAttribute = typeDetail.Attributes.Select(x => x as EntityAttribute).Where(x => x is not null).FirstOrDefault();
            if (sourceEntityAttribute is not null)
            {
                var storeName = sourceEntityAttribute.StoreName;
                if (String.IsNullOrWhiteSpace(storeName))
                    storeName = this.Type.Name;

                if (!storeName.All(x => Char.IsLetterOrDigit(x) || x == '_' || x == '`'))
                    throw new ArgumentException($"{nameof(EntityAttribute)}.{nameof(EntityAttribute.StoreName)}={this.DataSourceEntityName} is not a valid name");
                this.dataSourceEntityName = storeName;
            }

            var modelProperties = new List<ModelMemberDetail>();
            foreach (var member in typeDetail.Members)
            {
                if (!member.HasSetter || !member.HasGetter)
                    continue;
                var notSourcePropertyAttribute = member.Attributes.Select(x => x as StoreExcludeAttribute).Where(x => x is not null).FirstOrDefault();
                if (notSourcePropertyAttribute is null)
                {
                    var modelPropertyInfo = new ModelMemberDetail(member, this.IsDataSourceEntity);
                    modelProperties.Add(modelPropertyInfo);
                }
            }

            this.Name = typeDetail.Type.Name;
            this.Members = modelProperties.ToArray();

            this.membersByName = this.Members.ToDictionary(x => x.Name);
            this.membersByNameLower = this.Members.ToDictionary(x => x.Name.ToLower());
            this.IdentityMembers = this.Members.Where(x => x.IsIdentity).ToArray();
            this.IdentityAutoGeneratedMembers = this.Members.Where(x => x.IsIdentity && x.IsIdentityAutoGenerated).ToArray();
            this.RelatedMembers = this.Members.Where(x => x.IsRelated).ToArray();
            this.RelatedEnumerableMembers = this.Members.Where(x => x.IsRelated && x.IsEnumerable).ToArray();
            this.RelatedNonEnumerableMembers = this.Members.Where(x => x.IsRelated && !x.IsEnumerable).ToArray();
            this.NonAutoGeneratedNonRelationMembers = this.Members.Where(x => !x.IsIdentityAutoGenerated && !x.IsRelated).ToArray();

            this.Creator = typeDetail.CreatorBoxed!;
        }
    }
}
