// Copyright © KaKush LLC
// Written By Steven Zawaski
// Licensed to you under the MIT license

using System.Reflection;
using Zerra.Reflection;

namespace Zerra.Repository.Reflection
{
    /// <summary>
    /// Holds reflected metadata about a single property of a repository model type, including
    /// data-source mapping, identity, relation, and accessor delegates.
    /// </summary>
    public sealed class ModelPropertyDetail
    {
        /// <summary>
        /// The underlying <see cref="Zerra.Reflection.MemberDetail"/> for this property.
        /// </summary>
        public MemberDetail MemberDetail { get; }
        /// <summary>
        /// The <see cref="System.Reflection.MemberInfo"/> for this property.
        /// </summary>
        public MemberInfo MemberInfo { get; }
        /// <summary>
        /// Gets a value indicating whether the property's type is decorated with <see cref="EntityAttribute"/>.
        /// </summary>
        public bool IsDataSourceEntity { get; }
        /// <summary>
        /// The name of this property.
        /// </summary>
        public string Name { get; }
        /// <summary>
        /// The CLR <see cref="System.Type"/> of this property.
        /// </summary>
        public Type Type { get; }
        /// <summary>
        /// The <see cref="Zerra.Reflection.CoreType"/> classification of this property's type, if applicable.
        /// </summary>
        public CoreType? CoreType { get; }
        /// <summary>
        /// The column or store name for this property, as specified by <see cref="StoreNameAttribute"/> or defaulting to <see cref="Name"/>.
        /// </summary>
        public string PropertySourceName { get; }
        /// <summary>
        /// Gets a value indicating whether this property is marked with <see cref="IdentityAttribute"/>; typically maps to a database primary key.
        /// </summary>
        public bool IsIdentity { get; } //Usually maps to DB PrimaryKey
        /// <summary>
        /// Gets a value indicating whether the identity value is auto-generated by the data source (e.g. database auto-increment / identity specification).
        /// </summary>
        public bool IsIdentityAutoGenerated { get; } //Usually maps to DB Identity Specification (Auto Increment)
        /// <summary>
        /// Gets a value indicating whether this property is marked with <see cref="RelationAttribute"/>; indicates a foreign-key relationship.
        /// </summary>
        public bool IsRelated { get; }
        /// <summary>
        /// The name of the foreign-identity property on the related type, if this property is a relation; otherwise <see langword="null"/>.
        /// </summary>
        public string? ForeignIdentity { get; }
        /// <summary>
        /// Gets a value indicating whether this property's type implements <see cref="System.Collections.Generic.IEnumerable{T}"/> (i.e. a collection / one-to-many).
        /// </summary>
        public bool IsEnumerable { get; }
        /// <summary>
        /// Gets a value indicating whether this property's type is nullable.
        /// </summary>
        public bool IsNullable { get; }
        /// <summary>
        /// The element type for enumerable properties; otherwise the property type itself.
        /// </summary>
        public Type InnerType { get; }
        /// <summary>
        /// The <see cref="Zerra.Reflection.CoreType"/> classification of <see cref="InnerType"/>, if applicable.
        /// </summary>
        public CoreType? InnerCoreType { get; }
        /// <summary>
        /// Gets a value indicating whether the data-source column is stored as NOT NULL.
        /// </summary>
        public bool IsDataSourceNotNull { get; }
        /// <summary>
        /// The optional precision or maximum-length constraint for the data-source column, as specified by <see cref="StorePropertiesAttribute"/>.
        /// </summary>
        public int? DataSourcePrecisionLength { get; }
        /// <summary>
        /// The optional scale for numeric data-source columns, as specified by <see cref="StorePropertiesAttribute"/>.
        /// </summary>
        public int? DataSourceScale { get; }
        /// <summary>
        /// The <see cref="StoreTextEncoding"/> used when persisting string values in the data source.
        /// </summary>
        public StoreTextEncoding TextEncoding { get; }
        /// <summary>
        /// The <see cref="StoreDatePart"/> that controls which portion of a date/time value is persisted.
        /// </summary>
        public StoreDatePart DatePart { get; }

        /// <summary>
        /// A boxed delegate that gets the value of this property from a model instance.
        /// </summary>
        public Func<object, object?> GetterBoxed { get; }
        /// <summary>
        /// A boxed delegate that sets the value of this property on a model instance.
        /// </summary>
        public Action<object, object?> SetterBoxed { get; }

        /// <summary>
        /// A typed delegate that sets the value of this property on a model instance.
        /// </summary>
        public Delegate Setter { get; }

        /// <summary>
        /// A boxed factory delegate that creates a new instance of this property's type.
        /// </summary>
        public Func<object> CreatorBoxed { get; }

        /// <inheritdoc/>
        public override string ToString()
        {
            return $"{Type.Name} {Name}";
        }

        internal ModelPropertyDetail(MemberDetail memberDetail, bool declaringTypeIsDataSourceEntity)
        {
            this.MemberDetail = memberDetail;

            this.MemberInfo = memberDetail.MemberInfo;

            this.Name = memberDetail.Name;
            this.Type = memberDetail.Type;
            this.CoreType = memberDetail.TypeDetail.CoreType;
            this.IsNullable = memberDetail.TypeDetail.IsNullable;
            this.IsEnumerable = memberDetail.TypeDetail.HasIEnumerable;
            this.InnerType = MemberDetail.TypeDetail.CoreType != Zerra.Reflection.CoreType.String && memberDetail.TypeDetail.HasIEnumerable ? memberDetail.TypeDetail.IEnumerableGenericInnerType! : memberDetail.TypeDetail.Type;
            this.InnerCoreType = MemberDetail.TypeDetail.CoreType != Zerra.Reflection.CoreType.String && memberDetail.TypeDetail.HasIEnumerable && memberDetail.TypeDetail.IEnumerableGenericInnerTypeDetail!.CoreType.HasValue ? memberDetail.TypeDetail.IEnumerableGenericInnerTypeDetail!.CoreType : memberDetail.TypeDetail.CoreType;

            StoreNameAttribute? sourcePropertyAttribute = null;
            IdentityAttribute? identityAttribute = null;
            RelationAttribute? foreignIdentityAttribute = null;
            StorePropertiesAttribute? storePropertyAttribute = null;
            foreach (var attribute in memberDetail.Attributes)
            {
                if (attribute is StoreNameAttribute sourcePropertyAttributeFound)
                {
                    sourcePropertyAttribute = sourcePropertyAttributeFound;
                    continue;
                }
                if (declaringTypeIsDataSourceEntity)
                {
                    if (attribute is IdentityAttribute identityAttributeFound)
                    {
                        identityAttribute = identityAttributeFound;
                        continue;
                    }
                    if (attribute is RelationAttribute foreignIdentityAttributeFound)
                    {
                        foreignIdentityAttribute = foreignIdentityAttributeFound;
                        continue;
                    }
                }
                if (attribute is StorePropertiesAttribute storePropertyAttributeFound)
                {
                    storePropertyAttribute = storePropertyAttributeFound;
                    continue;
                }
            }

            EntityAttribute? entityAttribute = null;
            foreach (var attribute in memberDetail.TypeDetail.Attributes)
            {
                if (attribute is EntityAttribute entityAttributeFound)
                {
                    entityAttribute = entityAttributeFound;
                    break;
                }
            }

            var storeName = sourcePropertyAttribute?.StoreName;
            if (String.IsNullOrWhiteSpace(storeName))
                storeName = memberDetail.Name;
            if (!storeName.All(x => Char.IsLetterOrDigit(x) || x == '_' || x == '`'))
                throw new ArgumentException($"{nameof(StoreNameAttribute)}.{nameof(StoreNameAttribute.StoreName)}={storeName}");
            this.PropertySourceName = storeName;

            this.IsIdentity = identityAttribute is not null;
            this.ForeignIdentity = foreignIdentityAttribute?.ForeignIdentity;
            this.IsIdentityAutoGenerated = identityAttribute is not null && identityAttribute.AutoGenerated;
            this.IsRelated = foreignIdentityAttribute is not null;

            this.IsDataSourceEntity = entityAttribute is not null;

            this.IsDataSourceNotNull = storePropertyAttribute is not null ? storePropertyAttribute.NotNull : ((InnerType.IsValueType && !memberDetail.TypeDetail.IsNullable) && memberDetail.TypeDetail.CoreType != Zerra.Reflection.CoreType.String);
            this.DataSourcePrecisionLength = storePropertyAttribute is not null ? storePropertyAttribute.PrecisionLength : null;
            this.DataSourceScale = storePropertyAttribute is not null ? storePropertyAttribute.Scale : null;
            this.TextEncoding = storePropertyAttribute is not null ? storePropertyAttribute.TextEncoding : StoreTextEncoding.Unicode;
            this.DatePart = storePropertyAttribute is not null ? storePropertyAttribute.DatePart : StoreDatePart.DateTime;

            if (!this.IsDataSourceNotNull && this.IsIdentity)
                throw new Exception($"{this.Type.Name} {this.Name} cannot be both an identity and nullable");

            this.GetterBoxed = memberDetail.GetterBoxed;
            this.SetterBoxed = memberDetail.SetterBoxed;

            this.Setter = memberDetail.Setter;

            this.CreatorBoxed = this.MemberDetail.TypeDetail.CreatorBoxed;
        }
    }
}
