// Copyright © KaKush LLC
// Written By Steven Zawaski
// Licensed to you under the MIT license

using System.Linq.Expressions;

namespace Zerra.Repository
{
    /// <summary>
    /// A temporal query that retrieves multiple <typeparamref name="TModel"/> event records within an optional
    /// date or event-number range, with optional filtering, ordering, and pagination.
    /// </summary>
    /// <typeparam name="TModel">The type of model being queried.</typeparam>
    public class TemporalQueryMany<TModel> : QueryMany<TModel> where TModel : class, new()
    {
        /// <summary>Initializes a new instance filtering by date range; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo) : this(null, temporalDateFrom, temporalDateTo, null, null, null, null, null, null, null, null, null) { }
        /// <summary>Initializes a new instance filtering by date range with sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, QueryOrder<TModel>? order) : this(null, temporalDateFrom, temporalDateTo, null, null, null, null, null, order, null, null, null) { }
        /// <summary>Initializes a new instance filtering by date range with sort order and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, QueryOrder<TModel>? order, int? skip, int? take) : this(null, temporalDateFrom, temporalDateTo, null, null, null, null, null, order, skip, take, null) { }
        /// <summary>Initializes a new instance filtering by date range with a where expression; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, Expression<Func<TModel, bool>>? where) : this(null, temporalDateFrom, temporalDateTo, null, null, null, null, where, null, null, null, null) { }
        /// <summary>Initializes a new instance filtering by date range with a where expression and sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order) : this(null, temporalDateFrom, temporalDateTo, null, null, null, null, where, order, null, null, null) { }
        /// <summary>Initializes a new instance filtering by date range with a where expression, sort order, and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take) : this(null, temporalDateFrom, temporalDateTo, null, null, null, null, where, order, skip, take, null) { }

        /// <summary>Initializes a new instance filtering by date range with a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, Graph<TModel>? graph) : this(null, temporalDateFrom, temporalDateTo, null, null, null, null, null, null, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by date range with sort order and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(null, temporalDateFrom, temporalDateTo, null, null, null, null, null, order, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by date range with sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(null, temporalDateFrom, temporalDateTo, null, null, null, null, null, order, skip, take, graph) { }
        /// <summary>Initializes a new instance filtering by date range with a where expression and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, Expression<Func<TModel, bool>>? where, Graph<TModel>? graph) : this(null, temporalDateFrom, temporalDateTo, null, null, null, null, where, null, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by date range with a where expression, sort order, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(null, temporalDateFrom, temporalDateTo, null, null, null, null, where, order, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by date range with a where expression, sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(null, temporalDateFrom, temporalDateTo, null, null, null, null, where, order, skip, take, graph) { }

        /// <summary>Initializes a new instance filtering by date range with temporal pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake) : this(null, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, null, null, null, null, null) { }
        /// <summary>Initializes a new instance filtering by date range with temporal pagination and sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order) : this(null, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, null, order, null, null, null) { }
        /// <summary>Initializes a new instance filtering by date range with temporal pagination, sort order, and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order, int? skip, int? take) : this(null, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, null, order, skip, take, null) { }
        /// <summary>Initializes a new instance filtering by date range with temporal pagination and a where expression; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where) : this(null, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, where, null, null, null, null) { }
        /// <summary>Initializes a new instance filtering by date range with temporal pagination, a where expression, and sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order) : this(null, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, where, order, null, null, null) { }
        /// <summary>Initializes a new instance filtering by date range with temporal pagination, a where expression, sort order, and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take) : this(null, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, where, order, skip, take, null) { }

        /// <summary>Initializes a new instance filtering by date range with temporal pagination and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, Graph<TModel>? graph) : this(null, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, null, null, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by date range with temporal pagination, sort order, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(null, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, null, order, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by date range with temporal pagination, sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(null, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, null, order, skip, take, graph) { }
        /// <summary>Initializes a new instance filtering by date range with temporal pagination, a where expression, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, Graph<TModel>? graph) : this(null, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, where, null, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by date range with temporal pagination, a where expression, sort order, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(null, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, where, order, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by date range with temporal pagination, a where expression, sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(null, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, where, order, skip, take, graph) { }

        /// <summary>Initializes a new instance filtering by event number range; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo) : this(null, null, null, temporalNumberFrom, temporalNumberTo, null, null, null, null, null, null, null) { }
        /// <summary>Initializes a new instance filtering by event number range with sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, QueryOrder<TModel>? order) : this(null, null, null, temporalNumberFrom, temporalNumberTo, null, null, null, order, null, null, null) { }
        /// <summary>Initializes a new instance filtering by event number range with sort order and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, QueryOrder<TModel>? order, int? skip, int? take) : this(null, null, null, temporalNumberFrom, temporalNumberTo, null, null, null, order, skip, take, null) { }
        /// <summary>Initializes a new instance filtering by event number range with a where expression; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, Expression<Func<TModel, bool>>? where) : this(null, null, null, temporalNumberFrom, temporalNumberTo, null, null, where, null, null, null, null) { }
        /// <summary>Initializes a new instance filtering by event number range with a where expression and sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order) : this(null, null, null, temporalNumberFrom, temporalNumberTo, null, null, where, order, null, null, null) { }
        /// <summary>Initializes a new instance filtering by event number range with a where expression, sort order, and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take) : this(null, null, null, temporalNumberFrom, temporalNumberTo, null, null, where, order, skip, take, null) { }

        /// <summary>Initializes a new instance filtering by event number range with a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, Graph<TModel>? graph) : this(null, null, null, temporalNumberFrom, temporalNumberTo, null, null, null, null, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by event number range with sort order and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(null, null, null, temporalNumberFrom, temporalNumberTo, null, null, null, order, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by event number range with sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(null, null, null, temporalNumberFrom, temporalNumberTo, null, null, null, order, skip, take, graph) { }
        /// <summary>Initializes a new instance filtering by event number range with a where expression and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, Expression<Func<TModel, bool>>? where, Graph<TModel>? graph) : this(null, null, null, temporalNumberFrom, temporalNumberTo, null, null, where, null, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by event number range with a where expression, sort order, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(null, null, null, temporalNumberFrom, temporalNumberTo, null, null, where, order, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by event number range with a where expression, sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(null, null, null, temporalNumberFrom, temporalNumberTo, null, null, where, order, skip, take, graph) { }

        /// <summary>Initializes a new instance filtering by event number range with temporal pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake) : this(null, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, null, null, null, null, null) { }
        /// <summary>Initializes a new instance filtering by event number range with temporal pagination and sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order) : this(null, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, null, order, null, null, null) { }
        /// <summary>Initializes a new instance filtering by event number range with temporal pagination, sort order, and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order, int? skip, int? take) : this(null, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, null, order, skip, take, null) { }
        /// <summary>Initializes a new instance filtering by event number range with temporal pagination and a where expression; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where) : this(null, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, where, null, null, null, null) { }
        /// <summary>Initializes a new instance filtering by event number range with temporal pagination, a where expression, and sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order) : this(null, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, where, order, null, null, null) { }
        /// <summary>Initializes a new instance filtering by event number range with temporal pagination, a where expression, sort order, and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take) : this(null, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, where, order, skip, take, null) { }

        /// <summary>Initializes a new instance filtering by event number range with temporal pagination and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Graph<TModel>? graph) : this(null, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, null, null, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by event number range with temporal pagination, sort order, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(null, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, null, order, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by event number range with temporal pagination, sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(null, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, null, order, skip, take, graph) { }
        /// <summary>Initializes a new instance filtering by event number range with temporal pagination, a where expression, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, Graph<TModel>? graph) : this(null, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, where, null, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by event number range with temporal pagination, a where expression, sort order, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(null, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, where, order, null, null, graph) { }
        /// <summary>Initializes a new instance filtering by event number range with temporal pagination, a where expression, sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(null, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, where, order, skip, take, graph) { }

        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, null, null, null, null, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, QueryOrder<TModel>? order) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, null, null, null, order, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with sort order and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, QueryOrder<TModel>? order, int? skip, int? take) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, null, null, null, order, skip, take, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with a where expression; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, Expression<Func<TModel, bool>>? where) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, null, null, where, null, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with a where expression and sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, null, null, where, order, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with a where expression, sort order, and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, null, null, where, order, skip, take, null) { }

        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, Graph<TModel>? graph) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, null, null, null, null, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with sort order and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, null, null, null, order, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, null, null, null, order, skip, take, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with a where expression and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, Expression<Func<TModel, bool>>? where, Graph<TModel>? graph) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, null, null, where, null, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with a where expression, sort order, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, null, null, where, order, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with a where expression, sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, null, null, where, order, skip, take, graph) { }

        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with temporal pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, null, null, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with temporal pagination and sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, null, order, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with temporal pagination, sort order, and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order, int? skip, int? take) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, null, order, skip, take, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with temporal pagination and a where expression; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, where, null, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with temporal pagination, a where expression, and sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, where, order, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with temporal pagination, a where expression, sort order, and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, where, order, skip, take, null) { }

        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with temporal pagination and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, Graph<TModel>? graph) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, null, null, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with temporal pagination, sort order, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, null, order, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with temporal pagination, sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, null, order, skip, take, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with temporal pagination, a where expression, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, Graph<TModel>? graph) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, where, null, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with temporal pagination, a where expression, sort order, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, where, order, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by date range with temporal pagination, a where expression, sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(temporalOrder, temporalDateFrom, temporalDateTo, null, null, temporalSkip, temporalTake, where, order, skip, take, graph) { }

        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, null, null, null, null, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, QueryOrder<TModel>? order) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, null, null, null, order, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with sort order and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, QueryOrder<TModel>? order, int? skip, int? take) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, null, null, null, order, skip, take, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with a where expression; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, Expression<Func<TModel, bool>>? where) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, null, null, where, null, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with a where expression and sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, null, null, where, order, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with a where expression, sort order, and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, null, null, where, order, skip, take, null) { }

        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, Graph<TModel>? graph) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, null, null, null, null, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with sort order and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, null, null, null, order, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, null, null, null, order, skip, take, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with a where expression and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, Expression<Func<TModel, bool>>? where, Graph<TModel>? graph) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, null, null, where, null, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with a where expression, sort order, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, null, null, where, order, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with a where expression, sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, null, null, where, order, skip, take, graph) { }

        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with temporal pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, null, null, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with temporal pagination and sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, null, order, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with temporal pagination, sort order, and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order, int? skip, int? take) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, null, order, skip, take, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with temporal pagination and a where expression; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, where, null, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with temporal pagination, a where expression, and sort order; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, where, order, null, null, null) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with temporal pagination, a where expression, sort order, and pagination; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, where, order, skip, take, null) { }

        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with temporal pagination and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Graph<TModel>? graph) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, null, null, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with temporal pagination, sort order, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, null, order, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with temporal pagination, sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, null, order, skip, take, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with temporal pagination, a where expression, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, Graph<TModel>? graph) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, where, null, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with temporal pagination, a where expression, sort order, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, Graph<TModel>? graph) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, where, order, null, null, graph) { }
        /// <summary>Initializes a new instance with an explicit temporal order filtering by event number range with temporal pagination, a where expression, sort order, pagination, and a property graph; remaining parameters default to <see langword="null"/>.</summary>
        public TemporalQueryMany(TemporalOrder temporalOrder, ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph) : this(temporalOrder, null, null, temporalNumberFrom, temporalNumberTo, temporalSkip, temporalTake, where, order, skip, take, graph) { }

        /// <summary>
        /// Initializes a new instance with full temporal and query parameters.
        /// </summary>
        /// <param name="temporalOrder">The temporal ordering direction; defaults to <see cref="TemporalOrder.Newest"/> when <see langword="null"/>.</param>
        /// <param name="temporalDateFrom">The inclusive start date for temporal range filtering.</param>
        /// <param name="temporalDateTo">The inclusive end date for temporal range filtering.</param>
        /// <param name="temporalNumberFrom">The inclusive start event number for temporal range filtering.</param>
        /// <param name="temporalNumberTo">The inclusive end event number for temporal range filtering.</param>
        /// <param name="temporalSkip">The number of temporal events to skip.</param>
        /// <param name="temporalTake">The maximum number of temporal events to return.</param>
        /// <param name="where">An optional filter expression.</param>
        /// <param name="order">An optional sort order.</param>
        /// <param name="skip">The number of records to skip for pagination.</param>
        /// <param name="take">The maximum number of records to return.</param>
        /// <param name="graph">The property graph specifying which members to populate.</param>
        public TemporalQueryMany(TemporalOrder? temporalOrder, DateTime? temporalDateFrom, DateTime? temporalDateTo, ulong? temporalNumberFrom, ulong? temporalNumberTo, int? temporalSkip, int? temporalTake, Expression<Func<TModel, bool>>? where, QueryOrder<TModel>? order, int? skip, int? take, Graph<TModel>? graph)
            : base(where, order, skip, take, graph)
        {
            this.TemporalOrder = temporalOrder ?? Repository.TemporalOrder.Newest;
            this.TemporalDateFrom = temporalDateFrom;
            this.TemporalDateTo = temporalDateTo;
            this.TemporalNumberFrom = temporalNumberFrom;
            this.TemporalNumberTo = temporalNumberTo;
            this.TemporalSkip = temporalSkip;
            this.TemporalTake = temporalTake;
        }
    }
}