// Copyright � KaKush LLC
// Written By Steven Zawaski
// Licensed to you under the MIT license

using Xunit;
using MySqlConnector;
using System.Text;
using Zerra.Repository.Reflection;
using Zerra.Repository.MySql;

namespace Zerra.Repository.Test.MySql
{
    public class MySqlEngineTests
    {
        private static int ExecuteSql(string connectionString, string sql)
        {
            using (var connection = new MySqlConnection(connectionString))
            {
                connection.Open();
                using (var command = connection.CreateCommand())
                {
                    command.CommandText = sql;
                    return command.ExecuteNonQuery();
                }
            }
        }

        private static void DropDatabase(string connectionString)
        {
            var builder = new MySqlConnectionStringBuilder(connectionString);
            var testDatabase = builder.Database;
            builder.Database = "sys";
            var connectionStringForMaster = builder.ToString();
            using (var connection = new MySqlConnection(connectionStringForMaster))
            {
                connection.Open();
                using (var command = connection.CreateCommand())
                {
                    command.CommandText = $"SELECT CONCAT('KILL ', id, ';') FROM INFORMATION_SCHEMA.PROCESSLIST WHERE `db` = '{testDatabase}'; DROP DATABASE IF EXISTS {testDatabase};";
                    _ = command.ExecuteNonQuery();
                }
            }
        }

        [Entity("GuidIdentity")]
        public sealed class GuidIdentityModel
        {
            [Identity(true)]
            public Guid ID { get; set; }
            public string? Name { get; set; }
        }

        [Fact]
        public async Task TestAutoGeneratedGuidIdentityNotSupported()
        {
            //throws before connecting, so this needs no server
            var engine = new MySqlEngine("Server=localhost;Port=1;Database=None");
            var modelDetail = ModelAnalyzer.GetModel(typeof(GuidIdentityModel));
            var model = new GuidIdentityModel() { Name = "test" };

            _ = Assert.Throws<NotSupportedException>(() => engine.ExecuteInsertGetIdentities(model, null, modelDetail));
            _ = await Assert.ThrowsAsync<NotSupportedException>(() => engine.ExecuteInsertGetIdentitiesAsync(model, null, modelDetail));
        }

        [Fact]
        public async Task TestSequence()
        {
            var connectionString = MySqlTestSqlDataContext.ConnectionString;
            var engine = new MySqlEngine(connectionString);

            DropDatabase(connectionString);

            var modelTypes = new[] { typeof(TestTypesModel), typeof(TestRelationsModel) }.Concat(RelationPersistTests.ModelTypes).Concat(QueryParityTests.ModelTypes).ToArray();

            CodeFirstGeneration.Generate(engine, DataStoreGenerationType.CodeFirst, modelTypes);
            RepoTest.AssertSchemaMatchesModels(engine, modelTypes);

            RepoTest.TestSequenceTransactStore(engine);
            await RepoTest.TestSequenceTransactStoreAsync(engine);
            RelationPersistTests.TestSequence(engine);
            await RelationPersistTests.TestSequenceAsync(engine);
            QueryParityTests.TestSequence(engine);
            await QueryParityTests.TestSequenceAsync(engine);
            SchemaChangeTests.Test(engine, table => ExecuteSql(connectionString, $"DROP TABLE IF EXISTS `{table}`"));

            const string changeColumn = "ALTER TABLE `TestTypes` MODIFY `Int32Thing` bigint NULL";
            const string addColumn = "ALTER TABLE `TestTypes` ADD `DummyToMakeNullable` int NOT NULL";
            const string dropColumn = "ALTER TABLE `TestTypes` DROP COLUMN `ByteThing`";
            _ = ExecuteSql(connectionString, changeColumn);
            _ = ExecuteSql(connectionString, addColumn);
            _ = ExecuteSql(connectionString, dropColumn);

            CodeFirstGeneration.Generate(engine, DataStoreGenerationType.CodeFirst, modelTypes);
            RepoTest.AssertSchemaMatchesModels(engine, modelTypes);

            var sb = new StringBuilder();
            var modelDetails = ModelAnalyzer.GetModel(typeof(TestTypesModel));
            foreach (var property in modelDetails.Members)
            {
                if (property.IsIdentity || property.IsIdentityAutoGenerated || property.IsRelated)
                    continue;
                if (modelDetails.Members.Any(x => x.ForeignIdentity == property.Name))
                    continue;
                _ = sb.Append("ALTER TABLE `TestTypes` DROP COLUMN `").Append(property.StoreName).Append("`;\r\n");
            }
            var dropAllColumns = sb.ToString();

            _ = ExecuteSql(connectionString, dropAllColumns);

            CodeFirstGeneration.Generate(engine, DataStoreGenerationType.CodeFirst, modelTypes);
            RepoTest.AssertSchemaMatchesModels(engine, modelTypes);

            _ = sb.Clear();
            foreach (var property in modelDetails.Members)
            {
                if (property.IsIdentity || property.IsIdentityAutoGenerated || property.IsRelated)
                    continue;
                if (modelDetails.Members.Any(x => x.ForeignIdentity == property.Name))
                    continue;
                if (property.IsNullable)
                {
                    _ = sb.Append("ALTER TABLE `TestTypes` ADD `Junk").Append(property.StoreName).Append("` ");
                    MySqlEngine.WriteSqlTypeFromModel(sb, property);
                    _ = sb.Insert(sb.Length - 4, "NOT ");
                    _ = sb.Append(";\r\n");
                }
            }
            var addJunkColumns = sb.ToString();

            _ = ExecuteSql(connectionString, addJunkColumns);

            CodeFirstGeneration.Generate(engine, DataStoreGenerationType.CodeFirst, modelTypes);
            RepoTest.AssertSchemaMatchesModels(engine, modelTypes);

            DropDatabase(connectionString);
        }
    }
}
